[package]
name = "weld_native"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "weld_native"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.21.0"
lazy_static = "1.0"
weld = "0.4.0"
